### ISSUE TITLE
Movimiento

### ISSUE THREAD

**Issue by Ramaaa9461** [lobinuxsoft/lunar-lander-xD#1]
El movimiento esta muy bueno! pero se me hizo casi imposible aterrizar en una base, siendo la mecanica principal nose que tan bien estaria eso! 

Supongo que tal vez la camara se puede fijar en el objetivo y eso puede ayudar o le podes encontrar la vuelta, me pareceria que esta muy complicado el juego

**Comment by Lobinux** [comment]
Si bien la idea es buena no funciona tan bien como se piensa, ya hice la prueba y no funciona la camara usando una plataforma de punto fijo, cambie el tipo de camara de orbital a un tipo mas third penson.
